name: ghcapi-sample
version: 0.1.0.0
github: "githubuser/ghcapi-sample"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/githubuser/ghcapi-sample#readme>

dependencies:
  - base >= 4.7 && < 5
  - ghc
  - ghc-paths

ghc-options:
  - -Wall
  - -Wcompat
  - -Wredundant-constraints¶

executables:
  haskellwiki-ex1:
    main: example1.hs
    source-dirs: src/haskellwiki/example1

  haskellwiki-ex2:
    main: A.hs
    source-dirs: src/haskellwiki/example2
    when:
      - condition: false
        other-modules: B
    dependencies:
      - ghc-boot-th
    ghc-options:
      - -main-is A

  haskellwiki-ex3:
    main: example3.hs
    source-dirs: src/haskellwiki/example3

  core-ex1:
    main: example1.hs
    source-dirs: src/core/example1

  stg-ex1:
    main: example1.hs
    source-dirs: src/stg/example1
    dependencies:
      - containers
