name: ghcapi-sample
version: 0.1.0.0
github: "githubuser/ghcapi-sample"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/githubuser/ghcapi-sample#readme>

dependencies:
  - base >= 4.7 && < 5

executables:
  haskellwiki-ex1:
    main: Simple.hs
    source-dirs: src/HaskellWiki/Example1
    dependencies:
      - ghc
      - ghc-paths
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  haskellwiki-ex2:
    main: A.hs
    source-dirs: src/HaskellWiki/Example2
    when:
      - condition: false
        other-modules: B
    dependencies:
      - ghc
      - ghc-paths
      - ghc-boot-th
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is A

  haskellwiki-ex3:
    main: Interactive.hs
    source-dirs: src/HaskellWiki/Example3
    dependencies:
      - ghc
      - ghc-paths
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  core-ex1:
    main: Simple.hs
    source-dirs: src/Core/Example1
    dependencies:
      - ghc
      - ghc-paths
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  stg-ex1:
    main: Simple.hs
    source-dirs: src/Stg/Example1
    dependencies:
      - ghc
      - ghc-paths
      - containers
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
